# Description: A workflow that performs two actions ()
# Date: March 4, 2025
# Author: Sara McKim

name: Task Two

on:
  push:
    branches:
      - main

jobs:
  action1:
    name: Checkout Action
    runs-on: ubuntu-latest
    steps: 
      - name: Step One - Checkout Action
        uses: actions/checkout@v4

  action2:
    name: Java SetUp Action (Setting up JDK 11 for x64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64